# ripple Boot File (Auto-generated by VerityOS Builder)

import os
import sys
import time
import yaml
from pathlib import Path
import json
import base64
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from collections import Counter
from email.mime.text import MIMEText

# OpenAI imports and API key loading
import openai
from dotenv import load_dotenv
load_dotenv()
openai.api_key = os.getenv("OPENAI_API_KEY")

try:
    from colorama import init, Fore, Style
    init(autoreset=True)
except ImportError:
    class Dummy:
        def __getattr__(self, name): return ''
    Fore = Style = Dummy()

# Path to config.yaml in the same directory as this script
config_path = Path(__file__).parent / "config.yaml"

# === Load Config ===
with open(config_path, "r") as f:
    config = yaml.safe_load(f)

# === Interactive setup phase for bad_senders ===
import sys
phase = config.get("setup_phase", 0)
if phase == 0:
    known = config.get("known_senders", [])
    print("🛠️ Initial configuration: please review your known_senders list.")
    for i, s in enumerate(known, start=1):
        print(f"{i}. {s}")
    to_remove = input("Type the numbers of any senders to blacklist (comma-separated), or press ENTER to accept all: ").strip()
    if to_remove:
        indices = [int(x)-1 for x in to_remove.split(",") if x.strip().isdigit()]
        bad = config.get("bad_senders", [])
        for idx in sorted(indices, reverse=True):
            bad.append(known.pop(idx))
        config["bad_senders"] = bad
        config["known_senders"] = known
        print(f"🔒 Blacklisted senders: {bad}")
    else:
        print("✅ No senders blacklisted.")
    config["setup_phase"] = 1
    # Write changes and exit for restart
    with open(config_path, "w") as wf:
        yaml.safe_dump(config, wf)
    print("🔄 Configuration saved. Please restart Ripple to continue.")
    sys.exit(0)

# Pagination and draft state
current_important = []
page_size = 10
last_page = []
last_drafts = []

# Pagination state for known senders review
senders_page = 0
senders_page_size = 10

name = config.get("name", "Agent")
mode = config.get("mode", "command")
auto_task = config.get("auto_task", False)
memory_path = Path(config.get("memory_path", f"./memory/ripple"))
log_path = Path(config.get("log_path", f"./logs/ripple"))

memory_path.mkdir(parents=True, exist_ok=True)
log_path.mkdir(parents=True, exist_ok=True)

print(f"🔁 Booting {name} (mode: {mode})")
print(f"📂 Memory: {memory_path} | Logs: {log_path}")
print("🧠 Available commands: fetch, next, previous, senders, draft <n>, send <n>, archive, exit")

def log(entry):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path / "latest.log", "a") as f:
        f.write(f"[{timestamp}] {entry}\n")

class GmailConnector:
    SCOPES = [
        'https://www.googleapis.com/auth/gmail.modify',
        'https://www.googleapis.com/auth/contacts.readonly'
    ]

    def __init__(self, config):
        creds = None
        creds_path = Path(__file__).parent / "credentials.json"
        token_path = Path(config.get("token_path", "./token.json"))
        if token_path.exists():
            creds = Credentials.from_authorized_user_file(str(token_path), GmailConnector.SCOPES)
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                str(creds_path),
                GmailConnector.SCOPES,
                redirect_uri='urn:ietf:wg:oauth:2.0:oob'
            )
            # Manual console-based authentication for headless environments
            auth_url, _ = flow.authorization_url(prompt='consent')
            print(f"🔗 Please go to this URL to authorize:\n{auth_url}")
            code = input("Enter the authorization code here: ")
            flow.fetch_token(code=code)
            creds = flow.credentials
            with open(token_path, "w") as token_file:
                token_file.write(creds.to_json())
        self.service = build('gmail', 'v1', credentials=creds)
        self.page_token = None

    def fetch_unread(self, max_results=10):
        params = {'userId': 'me', 'q': 'is:unread', 'maxResults': max_results}
        if self.page_token:
            params['pageToken'] = self.page_token
        results = self.service.users().messages().list(**params).execute()
        self.page_token = results.get('nextPageToken')
        msgs = results.get('messages', [])
        messages = []
        for m in msgs:
            msg = self.service.users().messages().get(userId='me', id=m['id'], format='full').execute()
            payload = msg.get('payload', {})
            headers = {h['name']: h['value'] for h in payload.get('headers', [])}
            body = ''
            if 'parts' in payload:
                for part in payload['parts']:
                    if part.get('mimeType') == 'text/plain':
                        data = part['body'].get('data', '')
                        body = base64.urlsafe_b64decode(data).decode('utf-8')
            messages.append({
                "id": m['id'],
                "from": headers.get('From',''),
                "subject": headers.get('Subject',''),
                "snippet": msg.get('snippet',''),
                "body": body
            })
        return messages

    def summarize(self, messages):
        summary = f"🔍 Total unread: {len(messages)}"
        senders = list({m['from'] for m in messages})
        return summary, senders

    def prepare_drafts(self, messages):
        drafts = []
        for m in messages:
            drafts.append({
                "to": m["from"],
                "subject": f"Re: {m['subject']}",
                "body": f"Hello,\n\nThanks for reaching out about \"{m['subject']}\". I'll get back to you shortly.\n\nBest,\n{config.get('name')}"
            })
        return drafts

    def archive(self, messages):
        count = 0
        for m in messages:
            self.service.users().messages().modify(
                userId='me', id=m['id'], body={'removeLabelIds': ['UNREAD']}
            ).execute()
            count += 1
        return f"🗄 Archived {count} messages."

    def send_email(self, to, subject, body):
        # Create MIME message
        msg = MIMEText(body)
        msg['to'] = to
        msg['subject'] = subject
        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        sent_msg = self.service.users().messages().send(
            userId='me',
            body={'raw': raw}
        ).execute()
        return sent_msg.get('id')

connector = GmailConnector(config)



def update_known_senders():
    known = set(config.get("known_senders", []))
    bad = set(config.get("bad_senders", []))
    # Exclude any blacklisted senders from known
    known -= bad
    initialized = config.get("known_senders_initialized", False)

    if not initialized:
        # Heavy initial load: Sent, Inbox, Contacts
        sent_results = connector.service.users().messages().list(
            userId='me', labelIds=['SENT'], maxResults=200
        ).execute().get('messages', [])
        sent_senders = []
        for m in sent_results:
            msg = connector.service.users().messages().get(
                userId='me', id=m['id'], format='metadata', metadataHeaders=['To','Cc']
            ).execute()
            hdrs = {h['name']:h['value'] for h in msg.get('payload',{}).get('headers',[])}
            for hdr in ('To','Cc'):
                if hdr in hdrs:
                    for addr in hdrs[hdr].split(','):
                        sent_senders.append(addr.strip())

        inbox_results = connector.service.users().messages().list(
            userId='me', labelIds=['INBOX'], q='-category:promotions -category:social', maxResults=200
        ).execute().get('messages', [])
        inbox_senders = []
        for m in inbox_results:
            msg = connector.service.users().messages().get(
                userId='me', id=m['id'], format='metadata', metadataHeaders=['From']
            ).execute()
            hdrs = {h['name']:h['value'] for h in msg.get('payload',{}).get('headers',[])}
            inbox_senders.append(hdrs.get('From','').strip())

        # Contacts via People API
        token_path = Path(config.get("token_path","./token.json"))
        creds = Credentials.from_authorized_user_file(str(token_path), GmailConnector.SCOPES)
        people_service = build('people','v1',credentials=creds)
        connections = people_service.people().connections().list(
            resourceName='people/me', pageSize=200, personFields='emailAddresses'
        ).execute().get('connections', [])
        contact_emails = [c['emailAddresses'][0]['value'] for c in connections if c.get('emailAddresses')]

        active_contacts = [c for c in contact_emails if c in set(sent_senders+inbox_senders) and c not in bad]
        if active_contacts:
            new_known = sorted([s for s in active_contacts[:10] if s])
        else:
            freq = Counter(sent_senders+inbox_senders)
            top = [s for s,_ in freq.most_common(10)]
            filtered = [s for s in set(top)|known if s]
            new_known = sorted(filtered)

        # Remove any blacklisted senders from the new list
        new_known = [s for s in new_known if s not in bad]

        config["known_senders"] = new_known
        config["known_senders_initialized"] = True
        print(Fore.GREEN + Style.BRIGHT + "✅ known_senders initialized:" + Style.RESET_ALL)
        for s in new_known:
            print("  " + Fore.YELLOW + s + Style.RESET_ALL)
    else:
        # Lightweight incremental check: only recent unread
        messages = connector.fetch_unread(max_results=50)
        incremental = [m["from"] for m in messages]
        new = [s for s in incremental if s and s not in known and s not in bad]
        if new:
            known.update(new)
            config["known_senders"] = sorted(known)
            print(Fore.CYAN + "🔄 Appended new known_senders:" + Style.RESET_ALL)
            for s in new:
                print("  " + Fore.YELLOW + s + Style.RESET_ALL)

    # Persist config
    with open(config_path, "w") as f:
        yaml.safe_dump(config, f)

# Run update on boot
update_known_senders()

# Store the most recently prepared drafts for review/sending
last_drafts = []

def show_senders_page():
    global senders_page
    known = config.get("known_senders", [])
    total = len(known)
    start = senders_page * senders_page_size
    end = min(start + senders_page_size, total)
    page = known[start:end]
    print(f"📬 Known senders {start+1}-{end} of {total}:")
    for idx, s in enumerate(page, start=1):
        print(f"{idx}. {s}")
    print("🧠 Commands: 'remove <n>', 'nextsenders', 'prevsenders', 'senders save', or 'exit'")


def run_command():
    # Declare globals for state variables
    global config, last_page, last_drafts, senders_page, current_important, current_page
    while True:
        task = input(f"🧠 {name} > ").strip()
        # Load known_senders from config at the top of each loop
        known = set(config.get("known_senders", []))
        if task.lower() in ["exit", "quit"]:
            break
        elif task == "fetch":
            # Fetch the next 10 unread messages
            page = connector.fetch_unread(max_results=10)
            last_page = page
            if not page:
                print("⚠️ No more unread messages.")
            else:
                print(f"📥 Fetched {len(page)} unread messages:")
                for i, m in enumerate(page, start=1):
                    print(f"{i}. From: {m['from']} | Subject: {m['subject']}")
            print("🧠 Use 'next' to fetch the next 10 emails or 'draft <n>' to draft.")
        elif task.lower() in ["next", "more"]:
            # Fetch the next 10 unread messages
            page = connector.fetch_unread(max_results=10)
            last_page = page
            if not page:
                print("⚠️ No more unread messages.")
            else:
                print(f"📥 Fetched next {len(page)} messages:")
                for i, m in enumerate(page, start=1):
                    print(f"{i}. From: {m['from']} | Subject: {m['subject']}")
            print("🧠 Use 'next' to fetch more, 'draft <n>' to draft, or 'exit'.")
        elif task.lower() in ["previous", "prev"]:
            # Show the initial batch again
            messages = connector.fetch_unread(max_results=page_size)
            known = set(config.get("known_senders", []))
            page = [
                m for m in messages
                if m["from"] in known
                and "no-reply" not in m["from"].lower()
                and "noreply" not in m["from"].lower()
            ]
            last_page = page
            print(f"📥 Reset to first batch: Showing {len(page)} important messages:")
            for i, m in enumerate(page, start=1):
                print(f"{i}. From: {m['from']}\n   Subject: {m['subject']}\n   Snippet: {m['snippet']}\n")
            print("🧠 Use 'next' to see next batch, 'previous' to return here, or 'draft <n>' to draft.")
        elif task.startswith("draft"):
            parts = task.split()
            if len(parts) != 2 or not parts[1].isdigit():
                print("⚠️ Usage: draft <n> where n is the message number on the current page.")
            else:
                idx = int(parts[1]) - 1
                try:
                    m = last_page[idx]
                except IndexError:
                    print("⚠️ Invalid index.")
                    continue
                # Generate draft with OpenAI
                prompt = (
                    f"Write a professional email response to the following message:\n\n"
                    f"Subject: {m['subject']}\n\n{m['body'] or m['snippet']}\n\n"
                    "Keep it concise and courteous. "
                    "Omit any signature or closing salutation; we will append our own."
                )
                response = openai.chat.completions.create(
                    model="gpt-4o-mini",
                    messages=[{"role": "user", "content": prompt}]
                )
                draft_body = response.choices[0].message.content.strip()
                # Append signature from config
                signature = config.get("signature_name", config.get("name", ""))
                if signature:
                    draft_body = f"{draft_body}\n\nBest regards,\n{signature}"
                last_drafts = [{
                    "to": m["from"],
                    "subject": f"Re: {m['subject']}",
                    "body": draft_body
                }]
                print(Fore.CYAN + "📝 Generated Draft:" + Style.RESET_ALL)
                print(f"To: {m['from']}\nSubject: Re: {m['subject']}\n\n{draft_body}\n")
                print("🧠 Use 'send 1' to send this draft.")
        elif task.startswith("send "):
            try:
                idx = int(task.split()[1]) - 1
                d = last_drafts[idx]
                msg_id = connector.send_email(d['to'], d['subject'], d['body'])
                print(Fore.GREEN + f"✅ Draft {idx+1} sent (Message ID: {msg_id})" + Style.RESET_ALL)
            except (IndexError, ValueError):
                print("⚠️ Invalid draft number. Use 'draft' to list and 'send <n>' to send.")
        elif task == "archive":
            # Fetch unread messages and archive them
            messages = connector.fetch_unread()
            if hasattr(connector, "archive"):
                result = connector.archive(messages)
                print(result)
            else:
                print("📦 Archive command is under development.")
        elif task == "senders":
            senders_page = 0
            show_senders_page()
        elif task == "nextsenders":
            senders_page += 1
            show_senders_page()
        elif task == "prevsenders":
            if senders_page > 0:
                senders_page -= 1
            show_senders_page()
        elif task.startswith("remove "):
            # Allow multiple comma-separated indices
            args = task[len("remove "):].strip()
            indices = [int(x.strip()) - 1 for x in args.split(",") if x.strip().isdigit()]
            if indices:
                known = config.get("known_senders", [])
                bad = config.get("bad_senders", [])
                removed = []
                # Remove in reverse order to keep indices valid
                for idx in sorted(indices, reverse=True):
                    if 0 <= idx < len(known):
                        removed_sender = known.pop(idx)
                        bad.append(removed_sender)
                        removed.append(removed_sender)
                config["known_senders"] = known
                config["bad_senders"] = bad
                with open(config_path, "w") as wf:
                    yaml.safe_dump(config, wf)
                print(f"❌ Removed and blacklisted: {removed}")
                show_senders_page()
            else:
                print("⚠️ Usage: remove <n>,<m>,... where numbers refer to the sender number on the current page.")
        elif task == "senders save":
            # Finalize and return to main menu
            senders_page = 0
            print("✅ Known senders updated and saved.")
        else:
            print("⚠️ Unknown command. Available: fetch, next, draft <n>, send <n>, archive, exit.")

def run_chat():
    print("💬 Chat mode is under development.")

#
# def check_inbox():
#     inbox_path = Path(f"./agents/{name}/inbox")
#     archive_path = inbox_path / "archive"
#     inbox_path.mkdir(parents=True, exist_ok=True)
#     archive_path.mkdir(parents=True, exist_ok=True)
#
#     for msg_file in sorted(inbox_path.glob("*.msg")):
#         content = msg_file.read_text().strip()
#         log(f"INBOX MESSAGE: {msg_file.name}\n{content}")
#         print(f"\n📥 Message from inbox:\n{content}\n")
#         msg_file.rename(archive_path / msg_file.name)

if __name__ == "__main__":
    # check_inbox()
    if auto_task:
        print("🗂 Auto-task polling is not yet implemented.")

    if mode == "command":
        run_command()
    elif mode == "chat":
        run_chat()
    elif mode == "dual":
        print("🌀 Dual mode not fully supported. Falling back to command.")
        run_command()
    else:
        print("⚠️ Unknown mode. Exiting.")
