# builder_engine.py – VerityOS Agent Code Generator (v1.0)

import yaml
from pathlib import Path
import os
import time
import subprocess

def build_agent_boot(agent_manifest_path):
    if not Path(agent_manifest_path).exists():
        return f"❌ Manifest file not found at: {agent_manifest_path}"

    with open(agent_manifest_path, "r") as f:
        manifest = yaml.safe_load(f)

    name = manifest.get("name", "unknown")
    role = manifest.get("role", "assistant")
    version = manifest.get("version", "0.1")
    model = manifest.get("model", "gpt-3.5")
    mode = manifest.get("mode", "command")
    persona = manifest.get("persona", "You are an AI agent.")

    agent_dir = Path(f"/home/ubuntu/verityos/agents/{name.lower()}")
    agent_dir.mkdir(parents=True, exist_ok=True)
    script_path = agent_dir / "boot.py"

    config_data = {
        "name": name,
        "role": role,
        "version": version,
        "model": model,
        "mode": mode,
        "auto_task": False,
        "memory_path": str(agent_dir / "memory_system"),
        "log_path": str(agent_dir / "logs")
    }

    with open(agent_dir / "config.yaml", "w") as f:
        yaml.dump(config_data, f)

    with open(agent_dir / "manifest.yaml", "w") as f:
        yaml.dump({
            "name": name,
            "version": version,
            "role": role,
            "model": model,
            "description": f"{name} is a {role} agent in VerityOS."
        }, f)


    # Enhanced agent boot script template
    boot_template = f'''# {name} Boot File (Auto-generated by VerityOS Builder)

import os
import time
import yaml
from pathlib import Path

# === Load Config ===
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

name = config.get("name", "Agent")
mode = config.get("mode", "command")
auto_task = config.get("auto_task", False)
memory_path = Path(config.get("memory_path", f"./memory/{name.lower()}"))
log_path = Path(config.get("log_path", f"./logs/{name.lower()}"))

memory_path.mkdir(parents=True, exist_ok=True)
log_path.mkdir(parents=True, exist_ok=True)

print(f"🔁 Booting {{name}} (mode: {{mode}})")
print(f"📂 Memory: {{memory_path}} | Logs: {{log_path}}")

def log(entry):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path / "latest.log", "a") as f:
        f.write(f"[{{timestamp}}] {{entry}}\\n")

def run_command():
    while True:
        task = input(f"🧠 {{name}} > ").strip()
        if task.lower() in ["exit", "quit"]:
            break
        log(f"COMMAND: {{task}}")
        print(f"✅ Task received: {{task}}")

def run_chat():
    print("💬 Chat mode is under development.")

def check_inbox():
    inbox_path = Path(f"./agents/{{name}}/inbox")
    archive_path = inbox_path / "archive"
    inbox_path.mkdir(parents=True, exist_ok=True)
    archive_path.mkdir(parents=True, exist_ok=True)

    for msg_file in sorted(inbox_path.glob("*.msg")):
        content = msg_file.read_text().strip()
        log(f"INBOX MESSAGE: {{msg_file.name}}\\n{{content}}")
        print(f"\\n📥 Message from inbox:\\n{{content}}\\n")
        msg_file.rename(archive_path / msg_file.name)

if __name__ == "__main__":
    check_inbox()
    if auto_task:
        print("🗂 Auto-task polling is not yet implemented.")

    if mode == "command":
        run_command()
    elif mode == "chat":
        run_chat()
    elif mode == "dual":
        print("🌀 Dual mode not fully supported. Falling back to command.")
        run_command()
    else:
        print("⚠️ Unknown mode. Exiting.")
'''

    with open(script_path, "w") as f:
        f.write(boot_template)

    # --- Render agent_template.j2 and save as agents/{agent_name}/{agent_name}.py ---
    from jinja2 import Environment, FileSystemLoader

    # Setup Jinja2 environment
    env = Environment(loader=FileSystemLoader("/home/ubuntu/verityos/templates"))
    template = env.get_template("agent_template.j2")

    rendered_script = template.render(
        agent_name=name,
        agent_class=name.capitalize(),
        version=version,
        role=role,
        memory_path=str(agent_dir / "memory_system"),
        log_path=str(agent_dir / "logs")
    )

    agent_script_path = agent_dir / f"{name.lower()}.py"
    with open(agent_script_path, "w") as f:
        f.write(rendered_script)

    return f"✅ {name} agent boot.py generated at {script_path}"

# Optional CLI usage
def main():
    import sys
    if len(sys.argv) != 2:
        print("Usage: python3 builder_module.py [manifest_path]")
        return
    print(build_agent_boot(sys.argv[1]))

# --- PATCH: Add parse_command for .build agent [name] ---
def parse_command(user_input):
    from pathlib import Path
    import subprocess
    if user_input.startswith(".build agent "):
        agent_name = user_input.split(" ", 2)[2].strip()
        manifest_path = f"/home/ubuntu/verityos/agents/{agent_name}/manifest.yaml"
        builder_path = "/home/ubuntu/verityos/scripts/builder_module.py"
        if not Path(manifest_path).exists():
            agent_dir = Path(f"/home/ubuntu/verityos/agents/{agent_name}")
            agent_dir.mkdir(parents=True, exist_ok=True)
            default_manifest = {
                "name": agent_name,
                "role": "Agent",
                "version": "1.0",
                "model": "gpt-4",
                "mode": "command"
            }
            with open(manifest_path, "w") as f:
                yaml.dump(default_manifest, f)
        try:
            result = subprocess.run(["python3", builder_path, manifest_path], capture_output=True, text=True)
            return result.stdout.strip()
        except Exception as e:
            return f"🔥 VerityOS Error: {e}"

if __name__ == "__main__":
    main()