# right Boot File (Auto-generated by VerityOS Builder)

import os
import time
import yaml
from pathlib import Path

# === Load Config ===
with open("config.yaml", "r") as f:
    config = yaml.safe_load(f)

name = config.get("name", "Agent")
mode = config.get("mode", "command")
auto_task = config.get("auto_task", False)
memory_path = Path(config.get("memory_path", f"./memory/right"))
log_path = Path(config.get("log_path", f"./logs/right"))

memory_path.mkdir(parents=True, exist_ok=True)
log_path.mkdir(parents=True, exist_ok=True)

print(f"🔁 Booting {name} (mode: {mode})")
print(f"📂 Memory: {memory_path} | Logs: {log_path}")

def log(entry):
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    with open(log_path / "latest.log", "a") as f:
        f.write(f"[{timestamp}] {entry}\n")

def run_command():
    while True:
        task = input(f"🧠 {name} > ").strip()
        if task.lower() in ["exit", "quit"]:
            break
        log(f"COMMAND: {task}")
        print(f"✅ Task received: {task}")

def run_chat():
    print("💬 Chat mode is under development.")

def check_inbox():
    inbox_path = Path(f"./agents/{name}/inbox")
    archive_path = inbox_path / "archive"
    inbox_path.mkdir(parents=True, exist_ok=True)
    archive_path.mkdir(parents=True, exist_ok=True)

    for msg_file in sorted(inbox_path.glob("*.msg")):
        content = msg_file.read_text().strip()
        log(f"INBOX MESSAGE: {msg_file.name}\n{content}")
        print(f"\n📥 Message from inbox:\n{content}\n")
        msg_file.rename(archive_path / msg_file.name)

if __name__ == "__main__":
    check_inbox()
    if auto_task:
        print("🗂 Auto-task polling is not yet implemented.")

    if mode == "command":
        run_command()
    elif mode == "chat":
        run_chat()
    elif mode == "dual":
        print("🌀 Dual mode not fully supported. Falling back to command.")
        run_command()
    else:
        print("⚠️ Unknown mode. Exiting.")
