from pathlib import Path
import time
import yaml
from zipfile import ZipFile

def get_agent_report(config):
    agents_dir = Path(config["memory_path"]) / "agents"
    if not agents_dir.exists() or not any(agents_dir.iterdir()):
        return "No agents currently registered."
    agents = [f.stem for f in agents_dir.glob("*.yaml")]
    return "🧠 Registered Agents:\n" + "\n".join(f" - {a}" for a in agents)

def handle_agent_commands(user_input, config):
    # Paste all the agent-related command handlers here.
    # Start with .generate agent, .simulate build, .build agent, etc.
    # Be sure to adjust any use of "Path(...)" to include config paths.

    if user_input.startswith(".generate agent "):
        agent_name = user_input.split(" ", 2)[2].strip()
        base_path = Path(f"/home/ubuntu/verityos/agents/{agent_name}")
        memory_path = Path(f"/home/ubuntu/verityos/memory/{agent_name}")
        log_path = Path(f"/home/ubuntu/verityos/logs/{agent_name}")

        base_path.mkdir(parents=True, exist_ok=True)
        memory_path.mkdir(parents=True, exist_ok=True)
        log_path.mkdir(parents=True, exist_ok=True)

        boot_path = base_path / "boot.py"
        if not boot_path.exists():
            boot_code = f'''# {agent_name} boot.py generated by VerityOS
print("🔧 {agent_name} booted. Ready to serve Boss.")
'''
            boot_path.write_text(boot_code)

        sops_path = base_path / "sops.yaml"
        if not sops_path.exists():
            sops_path.write_text("# Add SOPs here for task routines\n")

        mem_txt = memory_path / "memory.txt"
        if not mem_txt.exists():
            mem_txt.touch()

        readme_path = base_path / "README.md"
        if not readme_path.exists():
            readme_path.write_text(f"# {agent_name}\nThis agent is part of VerityOS.")

        return f"✅ Generated agent scaffold for '{agent_name}'."

    # Continue extracting other agent-related commands...

    return None